### ISSUE TITLE
Migrate styling from Bootstrap to MUI v5

### ISSUE THREAD

**Issue by evanjscallan** [orcasound/orcahome#11]
For easier compatibility between Orcahome and related apps, it would appear that migrating existing styles from Bootstrap 4 to Material-UI would make the process a decent amount more modular and easier for cross-collaboration.

**Comment by evanjscallan** [comment]
That being said, since some customization is required--would templatizing certain custom MUI style overrides via a self-contained, higher-level component be a viable option?

**Comment by paulcretu** [comment]
We could definitely make our own small library of custom components once we've built a few. For example check out the [Link component](https://github.com/orcasound/orcasite/blob/d4efff2d344550ef7db268192d1b6be016eb4b90/ui/src/components/Link.tsx) in Orcasite that I grabbed from the MUI nextjs example app, components like these are good candidates for being bundled together in their own library and using across multiple projects. It's a bit of hassle to set up and maintain though so only worthwhile once we have enough custom components to share.

In the interim, the easiest way to manage style overrides is via the [MUI ThemeProvider](https://mui.com/customization/theming/#createtheme-options-args-theme). Check out the [theme.ts](https://github.com/orcasound/orcasite/blob/d4efff2d344550ef7db268192d1b6be016eb4b90/ui/src/styles/theme.ts) I set up for Orcasite. You can get a lot done with MUI to [customize components](https://mui.com/customization/theme-components/) without having to make component wrappers (of course sometimes it's still necessary).

**Comment by rodrickcalvin** [comment]
Anyone working on this?

**Comment by evanjscallan** [comment]
I've built one of the button components (which probably needs revision) but a lot of this should be open. Divyanshu has created a headed/footer so he may be a good person to coordinate with as well to start consolidating.

**Comment by paulcretu** [comment]
List of everywhere bootstrap is currently being used:

- [ ] [about.js](https://github.com/orcasound/orcahome/blob/master/src/pages/about.js#L6-L8)
- [ ] [getinvolved.js](https://github.com/orcasound/orcahome/blob/master/src/pages/getinvolved.js#L4-L6)
- [ ] [index.js](https://github.com/orcasound/orcahome/blob/master/src/pages/index.js#L5-L7)

Each of these pages is only using 3 bootstrap components: Button, Card, and CardColumn. Shouldn't be too much work to replace with the MUI equivalents. Once that's done we can remove bootstrap completely.

**Comment by hgordon6634** [comment]
@paulcretu @DivyanshuParwal - Is this issue still relevant given that Paul is currently working on migrating the styling from CSS to  CSS-in-JS? Issue #28

**Comment by DivyanshuParwal** [comment]
@hgordon6634 That styling issue is different. This is replacing the bootstrap with temporary MUI equivalents so that bootstrap can be removed completely. Am I right @paulcretu

**Comment by paulcretu** [comment]
Yup @DivyanshuParwal is correct. This one should be closed soon by @DivyanshuParwal's PR #40 

Also I'm not actively working on #28, that one is open for anyone to contribute to. Both of these issues are cross-cutting so I'm just keeping track of the progress as we work on them, when everything gets checked off the list we can close the issue (can involve multiple PRs)
