### ISSUE TITLE
Making CONTRIBUTING.md file for the orcahome

### ISSUE THREAD

**Issue by aayushsrivastava9760** [orcasound/orcahome#17]
Currently, there's no file explaining how to contribute and set up the website locally with all the commands and steps in a systematic order. It would be better if the CONTRIBUTING.md file is added explaining how to set up the website locally, report bugs, Provide feedback or Request features, etc.

**Comment by aayushsrivastava9760** [comment]
I would like to work on this issue kindly assign it to me .

**Comment by hgordon6634** [comment]
That would be great if we could have this made so that people can contribute easily! @aayushsrivastava9760

**Comment by ShwetKhatri2001** [comment]
@hgordon6634 I'd like to start my contributions to orcahome from this issue. So, you can assign it to me if its urgent.

**Comment by paulcretu** [comment]
Closing this issue because I will be handling it as part of #22. For dev setup instructions, the current `README` (generated by default with `create-next-app`) works fine
