### ISSUE TITLE
Website Redesign: "About Us" Page 1- Top- UI 

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#20]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "About Us" page **SO THAT** I can easily learn about Orcasound's current projects.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "About Us" Page. This Issue covers only the top image of the page (see image below).

NOTES: 
-Header/Footer already completed on different pull request #14 
-This is the UI only, the pages for the Project Widgets will be created separately and can be linked to later. 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound homepage **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290 
![image](https://user-images.githubusercontent.com/93286885/152074831-16be424e-e052-44f4-b3f6-8ab54eaf6fea.png)

**Comment by ShwetKhatri2001** [comment]
Hi  @hgordon6634 ! I'd like to contribute to this issue . I have good experience working in open source and converting UI designs to frontend code in Next.js.

**Comment by hgordon6634** [comment]
Hey @ShwetKhatri2001 ! We would love your help!! 

However, these issues aren't QUITE ready to go (I just created them and was getting feedback from our developer volunteers about them and need to make some tweaks and split them up more). They should be ready to work on around Wednesday of next week. 

For now, why don't you hop on our Slack and introduce yourself in the Homepage-Redesign channel :) That way I can let you know when the issues are ready to go! https://orcasound.slack.com/archives/C025AV698S0

**Comment by hgordon6634** [comment]
@MohitSharma-21 - This should be ready to go now. I'm making two more issue tickets for the about page

**Comment by MohitSharma-21** [comment]
ok. I'll start working on it @hgordon6634 .

**Comment by paulcretu** [comment]
- Resolved by #73
