### ISSUE TITLE
Website Redesign: "Learn" Page 1- Top- UI

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#21]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "Learn" page **SO THAT** I can easily learn about Orcas.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "Learn" Page. This Issue covers ONLY the top picture and links on the page (see image below). 

NOTES: 
-This is the UI only, links can be added at a later iteration
-Header/Footer already completed on different pull request #14 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound Learn page **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290 
![image](https://user-images.githubusercontent.com/93286885/152076127-fed01fb2-2a67-4290-86cf-403d3696178d.png)

**Comment by ShwetKhatri2001** [comment]
Hi  @hgordon6634 ! I'd like to contribute to this issue . I have good experience working in open source and converting UI designs to frontend code in Next.js.

**Comment by hgordon6634** [comment]
Hey @ShwetKhatri2001 ! We would love your help!! 

However, these issues aren't QUITE ready to go (I just created them and was getting feedback from our developer volunteers about them and need to make some tweaks and split them up more). They should be ready to work on around Wednesday of next week. 

For now, why don't you hop on our Slack and introduce yourself in the Homepage-Redesign channel :) That way I can let you know when the issues are ready to go! https://orcasound.slack.com/archives/C025AV698S0

**Comment by hgordon6634** [comment]
@Daggerhub - This is good to go, I will be adding two more user stories (issues) for the Learn page. This is just for the top part.

**Comment by paulcretu** [comment]
- Resolved by #73
