### ISSUE TITLE
Website Redesign: "About Us" Page 2- Header Project Widgets- UI

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#41]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "About Us" page **SO THAT** I can easily learn about Orcasound's current projects.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "About Us" Page. This Issue covers only the project widgets and text (see image below).

NOTES: 
-Header/Footer already completed on different pull request #14 
-This is the UI only, the pages for the Project Widgets will be created separately and can be linked to later. 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound homepage **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290
![image](https://user-images.githubusercontent.com/93286885/152075270-de42e5b0-5ced-40ed-ba89-72324045e71e.png)

**Comment by hgordon6634** [comment]
@MohitSharma-21 - Here is the other user story for the bottom half of the about page. You can work on it or unassign yourself and work on something else!

**Comment by MohitSharma-21** [comment]
I can work on it @hgordon6634 .
