### ISSUE TITLE
Website Redesign: "Get Involved" Page 2- Volunteer- UI

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#47]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "Get Involved" page **SO THAT** I can easily get involved in Orca conservation.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "Learn" Page. This Issue covers ONLY the Volunteer- Citizen Scientist/ In Person/ For Developers portion on the page (see image below). 

NOTES: 
-This is the UI only, links can be added at a later iteration
-Header/Footer already completed on different pull request #14 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound Get Involved page **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290 
![image](https://user-images.githubusercontent.com/93286885/152078406-810f0d26-a798-4115-8db6-a9ccd8f371b6.png)

**Comment by ShwetKhatri2001** [comment]
@hgordon6634 I'd like to start working on this issue
