### ISSUE TITLE
Website Redesign: "Blog" Page- UI

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#50]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "Blog" page **SO THAT** I can easily keep up with Orcasound news.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "Learn" Page. This Issue covers the entire page (see image below). 

NOTES: 
-This is the UI only, links can be added at a later iteration
-Header/Footer already completed on different pull request #14 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound Blog page **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290 
![image](https://user-images.githubusercontent.com/93286885/152078858-d1994498-ef30-4548-986d-4fdb30751436.png)

**Comment by rodrickcalvin** [comment]
@hgordon6634 can I be assigned this issue?
