### ISSUE TITLE
Website Redesign: "Donate" Page 1- Top- UI

### ISSUE THREAD

**Issue by hgordon6634** [orcasound/orcahome#51]
***User Story***
**AS** a New Orcahome user **I WANT** to see an easy to read webpage when I navigate to the Orcasound "Donate" page **SO THAT** I can easily donate to Orcasound's efforts.

***Description***
The intent of this story is to implement the UI finalized design from the Orcasound UX/UI team for the website redesign of the "Learn" Page. This Issue covers the top image and writing (see image below). 

NOTES: 
-This is the UI only, links can be added at a later iteration
-Header/Footer already completed on different pull request #14 
-Use Material UI for the styling 
 
***Acceptance Criteria***
**GIVEN** I open the Orcasound Donate page **WHEN** I look at the page **THEN** I see a UI that matches the attached UX/UI design.

https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcasound-Website-Redesign-2021?node-id=298%3A290 
![image](https://user-images.githubusercontent.com/93286885/152079149-38ddea01-af81-40d7-8e53-0769080a0625.png)

**Comment by ShwetKhatri2001** [comment]
@hgordon6634 I'd like to work on this issue next, as I have worked on quite a similar issue #46 already, so that we can maintain code consistency as well

**Comment by hgordon6634** [comment]
Sure @ShwetKhatri2001 ! Go ahead and assign yourself to this issue :)

**Comment by ShwetKhatri2001** [comment]
I'm not able to assign myself but have made a draft PR for this issue and will start working on it.

**Comment by hgordon6634** [comment]
I have assigned you @ShwetKhatri2001 !
