### ISSUE TITLE
Fix all lint warnings

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcahome#63]
There are currently over 40 lint warnings across 6 files

![image](https://user-images.githubusercontent.com/1069628/153057044-18dc11b7-b64e-47d3-b8ff-ece500058965.png)

### warnings

- [x] `@next/next/link-passhref`
- [x] `@next/next/no-page-custom-font`
- [x] `jsx-a11y/alt-text`
- [x] `jsx-a11y/anchor-is-valid`
- [x] `react/no-unescaped-entities`

### pages

- [x] `Footer.jsx`
- [x] `Nav.jsx`
- [x] `about.jsx`
- [x] `getinvolved.jsx`
- [x] `index.jsx`
- [x] `learn.jsx`

**Comment by ShwetKhatri2001** [comment]
@paulcretu  I'd like to work on this issue till my current PRs are under Review. I fixed some lint warnings while making those PRs and would like to fix it all now.

**Comment by rodrickcalvin** [comment]
@hgordon6634 can you assign me to help out with the tasks. I can knock off this ```jsx-a11y/alt-text``` error

**Comment by paulcretu** [comment]
@rodrickcalvin there'a already a PR for this (#65) so let me review that first and see if there's anything left to do on this issue
