### ISSUE TITLE
ActionButton component not fit into the  UX-design

### ISSUE THREAD

**Issue by hardco2020** [orcasound/orcahome#82]
## Problems
I was trying to solve the #43, when I tried to reuse the ActionButton components, I found out there are some setting on the button which will lead to some buttons not fit into the UX-design

## Reproduce the problem

**It supposed to be**
<img width="517" alt="截圖 2022-03-19 下午7 53 51" src="https://user-images.githubusercontent.com/61721490/159146000-f23f77ad-69ed-40dc-82d7-7779e0bfe1fe.png">

**But instead** 
<img width="1098" alt="截圖 2022-03-19 下午7 52 32" src="https://user-images.githubusercontent.com/61721490/159145977-d8a423b3-849b-4cf4-ad78-26971da7e69b.png">

## How to fix

By changing the color of the ActionButton and the padding and width setting, now it looks like 

<img width="1157" alt="截圖 2022-03-19 下午7 57 15" src="https://user-images.githubusercontent.com/61721490/159146094-c5aaf8e9-f869-458c-90c5-ad25613f3e4c.png">

I can see the ActionButton supposed to be a reusable button across the whole UI, so I changed it to fit into the UX-design.

**If this is indeed a part that hasn't been done, I will submit a PR regarding to the button change !**

Please correct me know if there's something wrong with above messages. Thank you!

**Comment by hardco2020** [comment]
@paulcretu  Please review, thanks!

**Comment by DivyanshuParwal** [comment]
@hardco2020 Go ahead and make a PR so we can review it.
