### ISSUE TITLE
Beta version of Orcahome

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/orcahome#89]
Orcahome (https://orcahome.netlify.app/) is almost ready for beta testing. This was a GSoC project that had some great momentum 2 summers ago, but has since stalled. This is a request to continue developing Orcahome so it can be beta tested and then launched as the new content website.

Figma file for design reference found here: https://www.figma.com/file/YdvbAjHETokV2x1LBHaElj/Orcahome-%2F-Orcasound-Website-Redesign-2021?node-id=298%3A290

Contact me at ux.brendan.thatcher@gmail.com with your email and request for Figma file access. I can also address any questions you may have about design specifications.

**Comment by scottveirs** [comment]
Here's a screenshot of the Figma for the record:
<img width="567" alt="Screen Shot 2022-12-21 at 4 32 37 PM" src="https://user-images.githubusercontent.com/14044595/209030444-b2d31ba3-ed74-4e03-8765-e5ebe00e4394.png">

Paul may have other thoughts, but here are resources and steps to consider in moving Orcahome towards beta-testing:

- [ ] Study classic projects (and ideally update them both)
- [ ] Merge, request changes, or reject on all pull requests
- [ ] Prioritize or close all outstanding issues
- [ ] Incorporate issues into a new (not classic) project for managing Orcahome going forward
- [ ] Teach content managers like me how to add content (via Markdown files or the CMS 
- [ ] Transfer content from old Wordpress site

**Comment by rodrickcalvin** [comment]
@UXBrendan and @scottveirs I am willing to work to build any frontend development required for the project. We can transfer the already existing data on WordPress to Headless WordPress (Trying to learn how to do this) so that it can act as a data source. This makes content management easy too. As if there's an already established template for specific content everyone can follow that.

@paulcretu what do you think?

**Comment by scottveirs** [comment]
Hey @rodrickcalvin -- I don't fully understand what you're proposing, but I think it sounds like an interesting solution. I'm reading through this [recent (Nov 22) discussion that is specific to Next.js and Vercel](https://vercel.com/guides/wordpress-with-vercel) both of which @imacchiavello selected during her valiant GSoC efforts.

Let us know if you found other good learning resources, or need us to dredge up more for you.

**Comment by rodrickcalvin** [comment]
@scottveirs that’s exactly what I meant. It’s great that it’s already in motion. Can’t wait to contribute.
